share/rocm/cmake/ROCMCreatePackage.cmake
Adding this CMAKE field so that dependencies are not automatically pulled in by RPMbuild.  Packages must explicit state their own dependencies (lower level rpm's are not accurately filling out their PROVIDES field).
=> Add CPACK_RPM_PACKAGE_AUTOREQPROV

share/rocm/cmake/ROCMInstallTargets.cmake
inl files are used in rocThrust and need to be packaged for this header only library.
=> Adding support for inl packaging for rocThrust 

share/rocm/cmake/ROCMSetupVersion.cmake
Usable by math libraries to manage the ABI version MAJOR parsing.
=> rocm_set_soversion added 

share/rocm/cmake/ROCMClangTidy.cmake
This provides a missing middle-ground between running clang-tidy on the entire project, and running clang-tidy on individual source files.
=> Add clang tidy target to check all sources related to the original target

README.md, share/rocm/cmake/ROCMCheckTargetIds.cmake
I've added a function that will check if the given list of target-ids are supported by the current CXX compiler, and return the subset that are.
=> Add rocm_check_target_ids

CHANGELOG.md, CMakeLists.txt
Suggestion to resolve #47.
Use the `write_basic_package_version_file` function from `CMakePackageConfigHelpers` to create a version file detectable by CMake. Installing this file with `install` ensures that it will also be correctly packaged.
=> Generate version file for cmake versioning

cmake-format.yaml, share/rocm/cmake/ROCMCreatePackage.cmake
Unfortunately this was missed in earlier testing, the "Suggests:" field used to smooth transitioning is not available on versions of rpmbuild prior to 4.12.0, which caused builds on Centos 7 to not generate the runtime package due to the invalid field. 
To pass the linter, the number of allowed branches was increased from 20 to 25.
=> Fix invalid "Suggests:" field on old rpmbuild

share/rocm/cmake/ROCMCreatePackage.cmake
Debian packages are incorrectly named with -devel, they should be named with -dev.
=> Rename debian DEVEL package to dev

share/rocm/cmake/ROCMCreatePackage.cmake
Add dependencies on the new rocm-core package by default.
Disable by setting ROCM_DEP_ROCMCORE to FALSE
=> Depend on rocm-core package

share/rocm/cmake/ROCMCreatePackage.cmake, test/libheaderonly/LICENSE, test/libsimple/LICENSE, test/libsimple2/LICENSE, test/version/LICENSE
If a license file was specified before calling rocm-create-package, install it to the correct location. If one wasn't specified, scan for a LICENSE(.*) file, then if one isn't found add it as the license file and install to the correct location.
=> Automatically install license

share/rocm/cmake/ROCMCreatePackage.cmake
The regex used contained \. to attempt to match a literal dot
character. This needed to be \\.
Change-Id: Ib15a4d130c6728981c50f34829c686521ac14251
=> Fix regular expression

CHANGELOG.md, CMakeLists.txt, doc/src/ROCMCreatePackage.rst, share/rocm/cmake/ROCMCreatePackage.cmake
Currently if a package doesn't specify a CPACK_GENERATOR the generated
one is excessive. rocBLAS generates several tarballs which are about
1GB in size each which are not used. This consumes I/O time slowing
the builds as well as using disk. Systems using "deb" files need to
install programs to create "rpm" packages and vice versa. With
generation of debug information these requirements become even more
stringent, for example the standard macros for packaging rpm debug
info require eu-strip to be installed.
If the build environment specifies a PKGTYPE variable and no
CPACK_GENERATOR is specified then set CPACK_GENERATOR based on this
value.
Change-Id: I14dcf59f6681d985f8e9ca25e68b4a3537835800
=> Create better default CPACK_GENERATOR

share/rocm/cmake/ROCMCreatePackage.cmake
The `rocm_set_cpack_gen` call needs to be moved to the original location of the code dealing with `CPACK_GENERATOR`, as some of the body of `rocm_create_package` modifies the `PARSE_COMPONENTS` variable. The current location does not see these modifications, and so does not generate components with them.
=> CPACK_GENERATOR fixes

share/rocm/cmake/ROCMHeaderWrapper.cmake
This check is unnecessary and incorrect, as it filters out all 2-letter directories when using this function.
=> Remove redundant check for parent directory

CHANGELOG.md, share/rocm/cmake/ROCMCheckTargetIds.cmake
Add support for target features for rocm_check_target ids. Before this change targets with target features specified (like xnack or sramecc) would fail. 
EDIT: the autodetection only fails (at least on clang) when `-Werror` is included in `CMAKE_CXX_FLAGS` because by default clang only issues a diagnostic not an error.
=> Make rocm_check_target_ids more robust

share/rocm/cmake/ROCMCreatePackage.cmake
Header-only libraries don't have a runtime component, unless the devel component isn't being used (e.g. on Windows). If the devel component isn't being used, then the runtime component should always be packaged.
=> Always create runtime package if not using devel component

share/rocm/cmake/ROCMInstallTargets.cmake
Alternative to #79, so that executable targets are not exported.
=> Don't export executable targets

.github/workflows/test.yml, share/rocm/cmake/ROCMInstallTargets.cmake, test/test.cmake
This is not compatible with CMake 3.10 (due to the use of generator expressions in `install(CODE)`, requiring the setting of `CMP0087`). Can anyone think of a better method to do the same thing?
=> Only link library specific files

share/rocm/cmake/ROCMCreatePackage.cmake
INFO is not a valid mode for CMake [`message`](https://cmake.org/cmake/help/latest/command/message.html), so it is interpreted as a plain string, printing "INFOrocm_set_cpack_gen didn't..." The message is not particularly useful anyway, so it might as well be removed.
=> Remove INFOrocm_set_cpack_gen message

share/rocm/cmake/header_template.h.in, test/CMakeLists.txt
Some of the upstream apps like Onnx-RT is failing compilation due to #warning.
Changing #warning to #pragma and it will be reverted back to #warning after 1-2 ROCm release
=> Changing #warning to #pragma message.

CHANGELOG.md, doc/src/ROCMHeaderWrapper.rst, share/rocm/cmake/header_template.h.in, test/pass/wrapper-nowarn.cmake
This is checks if `ROCM_NO_WRAPPER_HEADER_WARNING` is defined and applies the same logic as was already being used for `ROCM_@ITEM_GUARD@_GAVE_WARNING`. It basically exists so users can use a more meaningful define in their build code than `ROCM_SYMLINK_GAVE_WARNING` and `ROCM_WRAPPER_GAVE_WARNING`. The template header diff might look a bit messy because I inverted the if/else.
The `pass/wrapper-nowarn.cmake` tests were copied from `fail/wrapper.cmake` but had `-DROCM_NO_WRAPPER_HEADER_WARNING` added to their compiler flags. There's also minor fixes to the docs and I changed the comment style to be C89 compatible... just in case.
=> Add ROCM_NO_WRAPPER_HEADER_WARNING

share/rocm/cmake/ROCMCreatePackage.cmake
When not building RPM packages a warning about `rpm` still shows up when a development package is requested.
"CMake Warning at /opt/rocm/share/rocm/cmake/ROCMUtilities.cmake:50 (message): 
Could not determine the version of program rpmbuild."
As this is only an optional check used to add rpm specific dependency info to the package, it should be okay to silence this warning.
=> Silence RPM not found warning by adding QUIET

share/rocm/cmake/ROCMCreatePackage.cmake
Fix for python hooks. For libraries that don't install their python api by default this seems to break workflow for the uninstall/update procedure with these libraries.
=> ROCmCreatePackage: Fix pth uninstall

.github/workflows/test.yml
The GitHub runner `macos-10.15` is deprecated and will be removed as of August 30, 2022. Therefore, switching to use the `macos-11` runner.
=> Switch to test on `macos-11`

CMakeLists.txt, test/analyze/CMakeLists.txt, test/findpackagecheck/CMakeLists.txt, test/libbasic/CMakeLists.txt, test/libheaderonly/CMakeLists.txt, test/libsimple/CMakeLists.txt, test/libsimple2/CMakeLists.txt, test/libwrapper/CMakeLists.txt, test/toolchain-var/CMakeLists.txt, test/version/CMakeLists.txt
Set the languages of the projects to NONE explicitly, to avoid CMake defaulting to C and C++.
From [CMake command project() documentation](https://cmake.org/cmake/help/latest/command/project.html?highlight=project):
> By default C and CXX are enabled if no language options are given
- This speeds up the configuration by a small amount because cmake does not have to search for and verify the compilers.
- It also allows configuring the project when a C orC++ compilers are not available.
- Finally when the build of rocm-cmake is embedded in an other project (as in the case of rocRAND) it avoids errors caused by cmake selecting MSVC for the C compiler but Clang for the C++ compiler on windows.
=> Set project languages to NONE

share/rocm/cmake/ROCMCreatePackage.cmake
During upgrade, the .pth files are getting removed after installing the new pkg( rpm/deb). This is because the postun/prerm scriplets has no condition check for remove/uninstall Vs upgrade.
THose .pth files should be removed only during the remove/uninstall operation.
Since the same set of scriptlets are used for both RPM and DEB, two conditions are checked for remove/uninstall and files will be removed on any one condition is satisfied ( either for RPM or DEB uninstall).
Signed-off-by: Saravanan Solaiyappan <saravanan.solaiyappan@amd.com>
=> ROCmCreatePackage: Update to prerm/postun scriptlets

share/rocm/cmake/ROCMCreatePackage.cmake
Arguments to prerm script is referenced correctly inside the function in the script.
Signed-off-by: Saravanan Solaiyappan <saravanan.solaiyappan@amd.com>
=> ROCmCreatePackage: Bug fix in prerm scriptlet

share/rocm/cmake/header_template.h.in, test/CMakeLists.txt
We've had a couple releases as a message. It's time for this to become a warning.
Reverts RadeonOpenCompute/rocm-cmake#89.
=> Revert "Changing #warning to #pragma message. (#89)"

test/pass/rocm-find-program-version.cmake
Noticed this while working on #108.
The `rocm-find-program-version` test was failing at my machine because the cmake version I was using to configure rocm-cmake was not the first in my PATH.
Unlikely but possible would be that no cmake is found on the path at all, which would also lead to this test failing.
Use `${CMAKE_COMMAND}` that holds the full path to cmake to fix it.
Let me know If you think I should add this to #108, I felt like it was a separate issue.
=> Use ${CMAKE_COMMAND} for running cmake from tests

share/rocm/cmake/ROCMInstallTargets.cmake
from 5.2.0, hip and rocm will also add cmake file into `<ROCM>/<PACKAGE>/lib/cmake` (not just `<ROCM>/lib/cmake/<PACAKGE>`)
hiprand and rocrand reports `include could not find load file: ...`
The workaround is link the missing file from `<ROCM>/lib/cmake/<PACAKGE>` to `<ROCM>/<PACKAGE>/lib/cmake`  or use `-D<pacakge_lower_case>_DIR=<ROCM>/<PACKAGE>/lib/cmake` in CMake
Issue:
When cmake find the file inside `<ROCM>/<PACKAGE>/lib/cmake`, it will create issue about cmakefile non-found.
https://github.com/RadeonOpenCompute/rocm-cmake/blob/03ec8374afec9d96afb9cc817fb9258feb84ed32/share/rocm/cmake/ROCMInstallTargets.cmake#L289-L293
only adds the INCLUDE cmake into CONFIG_PACKAGE_INSTALL_DIR, which is `lib/cmake/<PACKAGE>`
and looks for the file from current cmake folder. ( …
=> Fix own cmake files - also create symlink from INCLUDE cmake

share/rocm/cmake/ROCMClangTidy.cmake
Color codes in the output of this command can cause the subsequent FILE(MD5 ...) commands to fail.
=> Disable color for clang tidy cache file command

test/pass/version-norepo.cmake, test/pass/version-parent.cmake
This changes the tests to only match the numeric component, like the implementation of rocm_setup_version. Prior to these changes, the actual value would be the commit hash but the expected value would be the long output of git describe (containing the name of the nearest tag, the number of commits since that tag, and the commit hash). i.e.,
expected: rocm-5.3.3-7-g8bc91a1
actual: g8bc91a1
This changes it to be:
expected: g8bc91a1
actual: g8bc91a1
I still don't understand why this only recently began failing on the CI and I don't have a clear understanding of what these tests are testing.
=> Fix version-norepo and version-parent tests

CHANGELOG.md, CMakeLists.txt
Add changelog entries and bump the version number. The ROCm 5.4 release was the first we were trying to follow the new branching model. I don't think we clearly stated that we would follow the same versioning practices as other libraries, but I think it's a good idea to ensure that upon release, if the git hash is different then the version number is different.
=> Update changelog and bump version number

share/rocm/cmake/ROCMClangTidy.cmake, test/analyze/CMakeLists.txt
In newer cmake it doesn't implicitly pass the flags along(this seemed to be an undocumented feature). Either way, I added `--` to fix this. 
Also, updated the tests to find these issues in the future.
=> Fix extra make flags passed for clang tidy

CHANGELOG.md, CMakeLists.txt
We should probably have done this sooner, but better late than never.
=> Update version number and changelog for ROCm 6.0

share/rocm/cmake/ROCMSphinxDoc.cmake
This should only be required when building the documentation. There is no reason to require it when users just wants to build the component.
=> Dont require sphinx to be installed

doc/src/ROCMSphinxDoc.rst, share/rocm/cmake/ROCMSphinxDoc.cmake
rocm-docs-core up until now assumed that during Sphinx documentation build the configure and source directories were the same. To allow use cases where project maintainers don't want to litter the source tree with build side-effects (understandable), this assumption is being cleaned up within rocm-docs-code (see [here](https://github.com/RadeonOpenCompute/rocm-docs-core/pull/409)).
This is the rocm-cmake side of supporting such use cases, allowing setting the `-c` flag of Sphinx. `conf.py` is searched either within this folder, or if not set, within the source tree, as was the case until now.
=> Allow separate source and config dirs in sphinx
